### PR TITLE
Fixed some of ili integration problems

### PR DESCRIPTION
**Pull request by iprotsyuk**
Changes are mainly done on the `ili side. In emperor, I removed unnecessary requirejs configs

### CODE REVIEW

**Comment by iprotsyuk** [comment]
A web-server is still needed for the time being, but `ili has become much more independent, so Emperor doesn't take care of `ili source files including css.

**Comment by ElDeveloper** [comment]
This works great, thanks!

Just noticed one thing, when I load a 3D model, there's an error message in the console:

```
Tab with ID "2D" is not present on the sidebar, but found in the file with visualization settings.
```

--------

Full output:

```
THREE.WebGLRenderer 83
bootstrap-slider.min.js:29 bootstrap-slider.js - WARNING: $.fn.slider namespace is already bound. Use the $.fn.bootstrapSlider namespace instead.
(anonymous) @ bootstrap-slider.min.js:29
(anonymous) @ bootstrap-slider.min.js:29
(anonymous) @ bootstrap-slider.min.js:29
execCb @ require-2.1.22.min.js:30
check @ require-2.1.22.min.js:18
enable @ require-2.1.22.min.js:24
init @ require-2.1.22.min.js:17
J @ require-2.1.22.min.js:14
completeLoad @ require-2.1.22.min.js:29
onScriptLoad @ require-2.1.22.min.js:30
three.min.js:155 THREE.WebGLRenderer 83
three.min.js:155 THREE.WebGLRenderer 83
Workspace.js:298 Task download completed in 15.872 sec
Workspace.js:298 Task load-measures completed in 0.317 sec
Workspace.js:298 Task load-mesh completed in 0.395 sec
Scene3D.js:428 Recoloring time: 0.004
Workspace.js:298 Task load-settings completed in 0.147 sec
AppSettingsController.js:96 Tab with ID "2D" is not present on the sidebar, but found in the file with visualization settings.
value @ AppSettingsController.js:96
_notify @ EventSource.js:24
(anonymous) @ Workspace.js:258
Workspace.js:298 Task map completed in 1.202 sec
Scene3D.js:428 Recoloring time: 0.017
```

**Comment by iprotsyuk** [comment]
Yeah, that's a known issue: I need to update some example files to eliminate it.

Regarding the need for running an HTTP server: now it's all about a couple of HTML template files, which get loaded by the `text` plugin of `Require.js`. Alternative solution, that I found could be renaming extension of files from `html` to `html.js`, s.t. they could be loaded as regular JS files by `Require.js` without any plugins. Internally, each file should contain some JS code which generates an HTML template as a string.
I'll do this today.

**Comment by ElDeveloper** [comment]
Excellent, thanks for the update!!!

**Pull request merged**
